// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7t7OQiNHDH81e4gNzKHb9LLqYHNlzpMA',
    appId: '1:562444895778:web:b11296c2006b3902b82c7b',
    messagingSenderId: '562444895778',
    projectId: 'flutter-miaplicacion',
    authDomain: 'flutter-miaplicacion.firebaseapp.com',
    storageBucket: 'flutter-miaplicacion.appspot.com',
    measurementId: 'G-TZJ03V6L6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKpTmOcCPiBl84iSftnkdgB5rJp1yvHrc',
    appId: '1:562444895778:android:9fcb3747cc0eb889b82c7b',
    messagingSenderId: '562444895778',
    projectId: 'flutter-miaplicacion',
    storageBucket: 'flutter-miaplicacion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHXuewLtkv7M0doRBbxzu0dhglJmbrhg8',
    appId: '1:562444895778:ios:24b6ac2e3d47d8b3b82c7b',
    messagingSenderId: '562444895778',
    projectId: 'flutter-miaplicacion',
    storageBucket: 'flutter-miaplicacion.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHXuewLtkv7M0doRBbxzu0dhglJmbrhg8',
    appId: '1:562444895778:ios:616adff86d5e6ba0b82c7b',
    messagingSenderId: '562444895778',
    projectId: 'flutter-miaplicacion',
    storageBucket: 'flutter-miaplicacion.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
