export 'package:my_app/pages/pagesHome/calculate.dart';
export 'package:my_app/pages/pagesHome/configuration.dart';
export 'package:my_app/pages/home.dart';
export 'package:my_app/pages/pagesHome/description.dart';
export 'package:my_app/pages/pagesHome/game.dart';
export 'package:my_app/pages/pagesHome/imagen.dart';
export 'package:my_app/pages/pagesHome/messages.dart';
export 'package:my_app/pages/pagesHome/store.dart';
export 'package:my_app/pages/pagesHome/FireBase/firebase.dart';